#Params: Telegram export of chat data in JSON format


#BitzaMTB
filename: BitzaMTB_220914_photo.result.json

mindate: 2019-01-01

#separate stat for the last year (number of days)
lastperiod: 365

#User name whos comments to extract 
username: Vlad B

#set to nonzero to use userid otherwise user will be searched by username  
userid: 0

#File where to put extracted user comments
commentsfilename: user-comments.txt
commentshtmlbook: user-comments.html


