#Params: Telegram export of chat data in JSON format

#Default
filename: result.json
mindate: 2019.1.1

#VeloBaza
#filename: Velobaza_20220909_result.json

#BitzaMTB
#filename: BitzaMTB_220914_photo.result.json

#User name whos comments to extract 
username: Vlad B

#set to nonzero to use userid otherwise user will be searched by username  
userid: 0

#File where to put extracted user comments
commentsfilename: user-comments.txt
commentshtmlbook: user-comments.html


